// VOTE

export const GET_VOTE_PROGRESS = "GET_VOTE_PROGRESS";
export const GET_VOTE_SUCCESS = "GET_VOTE_SUCCESS";
export const GET_VOTE_ERROR = "GET_VOTE_ERROR";

export const POST_VOTE_PROGRESS = "POST_VOTE_PROGRESS";
export const POST_VOTE_SUCCESS = "POST_VOTE_SUCCESS";
export const POST_VOTE_ERROR = "POST_VOTE_ERROR";

export const DELETE_VOTE_PROGRESS = "DELETE_VOTE_PROGRESS";
export const DELETE_VOTE_SUCCESS = "DELETE_VOTE_SUCCESS";
export const DELETE_VOTE_ERROR = "DELETE_VOTE_ERROR";
