// PARTY

export const GET_PARTY_PROGRESS = "GET_PARTY_PROGRESS";
export const GET_PARTY_SUCCESS = "GET_PARTY_SUCCESS";
export const GET_PARTY_ERROR = "GET_PARTY_ERROR";

export const POST_PARTY_PROGRESS = "POST_PARTY_PROGRESS";
export const POST_PARTY_SUCCESS = "POST_PARTY_SUCCESS";
export const POST_PARTY_ERROR = "POST_PARTY_ERROR";

export const DELETE_PARTY_PROGRESS = "DELETE_PARTY_PROGRESS";
export const DELETE_PARTY_SUCCESS = "DELETE_PARTY_SUCCESS";
export const DELETE_PARTY_ERROR = "DELETE_PARTY_ERROR";

export const UPDATE_PARTY_PROGRESS = "UPDATE_PARTY_PROGRESS";
export const UPDATE_PARTY_SUCCESS = "UPDATE_PARTY_SUCCESS";
export const UPDATE_PARTY_ERROR = "UPDATE_PARTY_ERROR";