// CONNECT

export const GET_CONNECT_PROGRESS = "GET_CONNECT_PROGRESS";
export const GET_CONNECT_SUCCESS = "GET_CONNECT_SUCCESS";
export const GET_CONNECT_ERROR = "GET_CONNECT_ERROR";

export const POST_CONNECT_PROGRESS = "POST_CONNECT_PROGRESS";
export const POST_CONNECT_SUCCESS = "POST_CONNECT_SUCCESS";
export const POST_CONNECT_ERROR = "POST_CONNECT_ERROR";

export const DELETE_CONNECT_PROGRESS = "DELETE_CONNECT_PROGRESS";
export const DELETE_CONNECT_SUCCESS = "DELETE_CONNECT_SUCCESS";
export const DELETE_CONNECT_ERROR = "DELETE_CONNECT_ERROR";
