export const GET_ELECTION_PROGRESS = "GET_ELECTION_PROGRESS";
export const GET_ELECTION_SUCCESS = "GET_ELECTION_SUCCESS";
export const GET_ELECTION_ERROR = "GET_ELECTION_ERROR";

export const POST_ELECTION_PROGRESS = "POST_ELECTION_PROGRESS";
export const POST_ELECTION_SUCCESS = "POST_ELECTION_SUCCESS";
export const POST_ELECTION_ERROR = "POST_ELECTION_ERROR";

export const DELETE_ELECTION_PROGRESS = "DELETE_ELECTION_PROGRESS";
export const DELETE_ELECTION_SUCCESS = "DELETE_ELECTION_SUCCESS";
export const DELETE_ELECTION_ERROR = "DELETE_ELECTION_ERROR";

export const UPDATE_ELECTION_PROGRESS = "UPDATE_ELECTION_PROGRESS";
export const UPDATE_ELECTION_SUCCESS = "UPDATE_ELECTION_SUCCESS";
export const UPDATE_ELECTION_ERROR = "UPDATE_ELECTION_ERROR";